Some updates
massimoaria/openalexR pull request #12
Opened 2022-09-05 18:23 UTC by trangdata

- [ ] I would like to be updated to the "aut" role (more [here](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf)) Would that be okay?
- [ ] New vignette following [this tutorial](https://github.com/ourresearch/openalex-api-tutorials/blob/develop/notebooks/institutions/oa-percentage.ipynb)
- [ ] Fixes for group_by to work

2022-09-06 00:21 UTC, trangdata commented
@massimoaria  Ready for review! 🙏🏽

2022-09-06 16:19 UTC, massimoaria requested changes

2022-09-06 16:19 UTC, massimoaria commented on R/oaApiRequest.R
> +  query_ls <- list("per-page" = 200) # TODO did we mean for this to be 1???
"per-page" is 1 because here the request is just to figure out how many items are returned by the query.
Then to reduce the query time, we ask for a single page with a single item.
There is no sense in downloading information about 200 items just to know the total number of items returned by the query.
With "per-page=1" the query will download the query metadata and only one record while with "per-page=200" the query will download 200 records in addition to the metadata.
If "count_only = TRUE" the function will return only thee metadata otherwise the function will download all the pages of the query by setting (in the for loop) the argument "per-page" to the value chosen at the user or to the default 200.

Then, in my opinion, it is correct to set "per-page" = 1.

2022-09-06 16:19 UTC, massimoaria commented on R/oaApiRequest.R
> +oa_random <- function(entity = oa_entities(),
It is not clear to me the usefulness of a function that allows you to download a random query. I do not understand its usefulness but still I am not against its introduction if you think it is interesting.

2022-09-06 16:25 UTC, trangdata commented on R/oaApiRequest.R
> +  query_ls <- list("per-page" = 200) # TODO did we mean for this to be 1???
Thank you for this explanation! 🙏🏽  That makes sense.

I changed it to 200 because if we perform the query with group_by, setting list("per-page" = 1) gives an error because group_by defaults to 200. But I will take care of the group_by case separately.

2022-09-06 16:37 UTC, trangdata commented on R/oaApiRequest.R
> +  query_ls <- list("per-page" = 200) # TODO did we mean for this to be 1???
Fixed in f94b402.

2022-09-09 00:25 UTC, trangdata commented
@massimoaria  Any chance you can take a quick look and approve the change? If you would still want to remove oa_random() I can do that too!

2022-09-09 13:46 UTC, massimoaria approved these changes

2022-09-09 13:47 UTC, merged